# Workflow name
name: Deploy App

# Events that call the workflow
on:
  workflow_call:
    inputs:
      typeDeploy:
        description: 'The type of deploy passed from the caller workflow'
        default: ''
        required: true
        type: string
      appName:
        description: 'The application name passed from the caller workflow'
        default: ''
        required: true
        type: string
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy to Amazon ECS job
  deploy ECS:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download task definition
        run: |
        aws ecs describe-task-definition --task-definition ${{ inputs.appName }} --query taskDefinition > task-definition.json

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
