# Workflow name
name: Deploy App

# Events that call the workflow
on:
  workflow_call:
    inputs:
      typeDeploy:
        description: 'The type of deploy passed from the caller workflow'
        default: ''
        required: true
        type: string
      appName:
        description: 'The application name passed from the caller workflow'
        default: ''
        required: true
        type: string
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true
  workflow_dispatch:

env:
  AWS_REGION: ${{ github.event.inputs.setRegion }}                                                      # set this to your preferred AWS region, e.g. us-west-1
  ENV: ${{ github.event.inputs.setEnvironment }} 
  APP_NAME: ${{ inputs.appName }}
  ENVIRONMENT_NAME: ${{ github.event.inputs.appName }}-${{ github.event.inputs.setEnvironment }}
  VERSION_LABEL: ${{ github.event.inputs.appName }}-${{ github.event.inputs.setEnvironment }}-${{ github.sha }}-${{github.run_number}}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy to Amazon ECS job
  deploy ECS:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download task definition
        run: |
        aws ecs describe-task-definition --task-definition ${{ inputs.appName }} --query taskDefinition > task-definition.json

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
  deploy Beanstalk:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Amazon Beanstalk
        run: |
        aws s3 cp ./app/app.zip s3://$ENVIRONMENT_NAME-bucket/$ENV/$VERSION_LABEL
        aws --region $AWS_REGION elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $VERSION_LABEL --source-bundle S3Bucket=$ENVIRONMENT_NAME-bucket,S3Key=$ENV/$VERSION_LABEL
        aws --region $AWS_REGION elasticbeanstalk update-environment --environment-name $ENVIRONMENT_NAME --version-label $VERSION_LABEL
  deploy Cloudfront:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Application
      run: |
        aws s3 sync --no-follow-symlinks app/ s3://$APP_NAME-$ENV-bucket/